### PR TITLE
Magento v1.9.3.5

### PR DESCRIPTION
**Pull request by JamesAllwood**

### CODE REVIEW

**Comment by flancer64** [comment]
Probably [1.9.3.6](https://magento.com/tech-resources/download?_ga=2.165486207.1154475359.1505449016-1534411243.1504439640#download2071)? Version 1.9.3.5 is skipped in Magento downloads.

**Comment by avoelkl** [comment]
Hi,

Is it possible that this is INDEED 1.9.3.5 that @JamesAllwood downloaded which has been tagged as 1.9.3.6 in this repo?

https://github.com/bragento/magento-core/blob/1.9.3.6/app/Mage.php#L168 shows 1.9.3.5.
1.9.3.5 was only online for a short time and then taken down again.

Just downloaded the .zip from magento.com/download which shows 1.9.3.6 correctly in Mage.php.

**Comment by adamj88** [comment]
@avoelkl looks that way, the comparison shows just the 1.9.3.5 commit/MR: https://github.com/bragento/magento-core/compare/1.9.3.4...1.9.3.6

**Comment by davidverholen** [comment]
Oh OK. I will remove this tag for now and try to fix the repo later

**Comment by flancer64** [comment]
image

**Comment by aschrammel** [comment]
Sent a PR targeting this issue :)

**Pull request merged**
