### PR TITLE
 SUPEE-11219 1.7

### PR DESCRIPTION
**Pull request by luckyraul**

### CODE REVIEW

**Comment by luckyraul** [comment]
@davidverholen tag please

**Comment by luckyraul** [comment]
@davidverholen also fix please 1.7.0.2-patch17 points to 1.9.4.3 commit

**Comment by davidverholen** [comment]
oh wow, sry. Forgot to switch branches for the release

**Comment by davidverholen** [comment]
@luckyraul I deleted the patch17 version and created a new patch18 version to make sure it gets updated if 17 already has been installed

**Pull request merged**
